name: LLMSecOps CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Free disk space
      run: |
        sudo rm -rf /usr/local/lib/android
        docker system prune -af || true    

    - name: Build Docker image
      run: docker build -t fastapi-app .

    - name: Verify Docker container runs
      run: |
        docker run -d -p 8000:8000 fastapi-app
        sleep 5
        docker ps -a
