name: LLMSecOps CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write    
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Free disk space
      run: |
        sudo rm -rf /usr/local/lib/android
        docker system prune -af || true    

    # Build & Push Image to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build & Push Docker image 
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest,${{ secrets.DOCKER_USERNAME }}/fastapi-app:${{ github.sha }}  

    - name: Free disk space before Trivy
      run: |
        sudo rm -rf /usr/local/lib/android
        docker system prune -af || true
        df -h
      
    # Add Trivy security scan here
    - name: Run Trivy vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
        scanners: 'vuln'
        exit-code: '0'

    - name: Upload Trivy results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Verify Docker container runs
      run: |
        docker run -d -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
        sleep 5
        docker ps -a
